### PR TITLE
added emacs

### PR DESCRIPTION
**Pull request by dg-shadow**

### CODE REVIEW

**Comment by AndriyPt** [comment]
@dg-shadow it will be nice having emacs in ide image which is base image for changed Dockerfiles (as @toliver suggested)

**Comment by dg-shadow** [comment]
It seems silly to have to add it to all the ide images rather than the base one. It should be available on any installation. Do you have an opinion on this @ugocupcic ?

**Comment by dg-shadow** [comment]
Or am I misunderstanding? Is there only one (well two, indigo+kinetic) ide image... I thought there were multiple ones. Either way I don't understand why it's a bad idea to add it to the base image...

**Comment by AndriyPt** [comment]
There is the same amount of IDE images as the base images. Just two https://github.com/shadow-robot/sr-build-tools/blob/master/docker/ros/indigo/ide/Dockerfile and https://github.com/shadow-robot/sr-build-tools/blob/master/docker/ros/kinetic/ide/Dockerfile . The rest of the IDE images are inherited from these two. If emacs is not big installation and there is a need for it in plain docker it might be the case. But if you are using it for development IDE images are the best place to go :) My main concern is size of the base image and possible version conflicts of the packages because we have too much software in it.

**Comment by dg-shadow** [comment]
I've moved it to IDE anyway, because that will serve my purposes but I still think it should be in base :P I (and others) use it as my preferred editor for any task, not just development... It's ~100mb, so hardly a large addition to the image size.

**Pull request merged**
