### PR TITLE
Remove -B option from git checkout

### PR DESCRIPTION
**Pull request by toliver**

### CODE REVIEW

**Comment by ugocupcic** [comment]
the `-B` creates the branch if it doesn't exist and pulls it otherwise. If we remove it it won't create it if the branch is missing (e.g. when starting working on a new hand). Why did you want to remove it?

**Comment by toliver** [comment]
Because it doesn't pull it from origin. If it doesn't exist locally it creates a new one from <start point>. If you don't specify start point I guess it takes that main branch HEAD.

**Comment by ugocupcic** [comment]
OK so that command will fail if the branch doesn't exist. May be it's a good thing ? (@jlaforga what do you think? You'd always have to create the branch before running the curl script for setting up a new production machine, which kind of makes sense since you're doing the tuning on your own machines right?)

**Comment by toliver** [comment]
No no, it doesn't fail. It succeeds in creating a new branch called `whatever_name` you pass, but that branch is pointing to the HEAD of indigo-devel, not to `origin/whatever_name`.

**Comment by ugocupcic** [comment]
```
git checkout dummy
error: pathspec 'dummy' did not match any file(s) known to git.
```


Is that just due to my git config?

**Comment by toliver** [comment]
Sorry, I misunderstood what you meant. My last comment was about -B.

I agree with your previous comment.

**Pull request merged**
