### PR TITLE
F add test process documentation

### PR DESCRIPTION
**Pull request by VahidAminZ**

### CODE REVIEW

**Comment by AndriyPt** [comment]
@VahidAminZ looks good. I would add section how to connect to desktop of the docker images using client e.g. Remmina

**Comment by toliver** [comment]
@VahidAminZ Do you think it's easy to add what @AndriyPt suggests?
Otherwise let's create a separate issue for that.

**Comment by AndriyPt** [comment]
@toliver we have tried that. It is not trivial and actually is not needed. UI installation is better to test on full VM

**Comment by toliver** [comment]
Is this ready to be merged then?

**Comment by VahidAminZ** [comment]
I think it is. Unless @AndriyPt thinks it can have more added to it.

**Pull request merged**
