### PR TITLE
F#249 add blockly to dev machine install

### LINKED ISSUE #249: Add blockly to dev and prod machine install

### PR DESCRIPTION
**Pull request by VahidAminZ**
fixes #249

### CODE REVIEW

**Comment by AndriyPt** [comment]
what about desktop shortcuts creation for production installation?

**Comment by VahidAminZ** [comment]
Indeed. Forgot about that.

**Comment by toliver** [comment]
Is this considered ready to merge?

**Comment by AndriyPt** [comment]
not yet, waiting for @VahidAminZ testing results :)

**Comment by ugocupcic** [comment]
any news on this one?

**Comment by AndriyPt** [comment]
not yet

**Pull request merged**
