### PR TITLE
add autopic rosinstall file

### PR DESCRIPTION
**Pull request by kirstyellis**

### CODE REVIEW

**Comment by ugocupcic** [comment]
Just to be sure: those packages are not needed for compiling / running autopic ? If they are dependencies listed in the different package.xml of autopic then they should go in the [repository.rosinstall](https://github.com/shadow-robot/autopic/blob/indigo-devel/repository.rosinstall) for the CI tools to work.

**Comment by toliver** [comment]
@ugocupcic wouldn't this be the same case as [stiff-flop](https://github.com/shadow-robot/sr-build-tools/blob/master/data/projects/stiff_flop-indigo.rosinstall)?

**Comment by ugocupcic** [comment]
Indeed :) I should have put those in the repo rosinstall from stiff flop (basically when you work on stiff flop or autopic, you should not be changing the deps). I'll move them around

**Comment by ugocupcic** [comment]
https://github.com/shadow-robot/stiff_flop/pull/226

**Pull request merged**
